{
  # External DNS still has to be provisioned at the registrar (out of scope for
  # dns.dynamicAAAA, which only manages the AAAA record): an MX for nomath.org
  # -> mail.nomath.org, an SPF TXT, the DKIM TXT that maddy prints on first
  # start, a DMARC TXT, and a PTR for the host's IPv6 address. Without these,
  # remote servers will reject mail from this host.
  systems.tower.modules = [
    (
      { config, ... }:
      let
        fqdn = "mail.nomath.org";
        domain = "nomath.org";
        bindDn = "uid=admin,ou=people,dc=nomath,dc=org";
        bindPasswordFile = config.age.secrets.lldap-admin-password.path;
      in
      {
        services.maddy = {
          enable = true;
          hostname = fqdn;
          primaryDomain = domain;
          localDomains = [ domain ];
          openFirewall = true; # 25 (SMTP), 143 (IMAP+STARTTLS), 587 (submission)

          tls = {
            loader = "file";
            certificates = [
              {
                certPath = "/var/lib/acme/${fqdn}/fullchain.pem";
                keyPath = "/var/lib/acme/${fqdn}/key.pem";
              }
            ];
          };

          secrets = [ "/run/maddy-ldap/env" ];

          config = ''
            auth.ldap local_authdb {
              urls ldap://127.0.0.1:3890
              bind plain "${bindDn}" "{env:LLDAP_BIND_PW}"
              base_dn "ou=people,dc=nomath,dc=org"
              filter "(&(objectClass=person)(|(uid={username})(mail={username})))"
              starttls off
            }

            storage.imapsql local_mailboxes {
              driver sqlite3
              dsn imapsql.db
            }

            table.chain local_rewrites {
              optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
              optional_step static {
                entry postmaster postmaster@$(primary_domain)
              }
              optional_step file /etc/maddy/aliases
            }

            msgpipeline local_routing {
              destination postmaster $(local_domains) {
                modify {
                  replace_rcpt &local_rewrites
                }
                deliver_to &local_mailboxes
              }
              default_destination {
                reject 550 5.1.1 "User doesn't exist"
              }
            }

            smtp tcp://0.0.0.0:25 {
              limits {
                all rate 20 1s
                all concurrency 10
              }
              dmarc yes
              check {
                require_mx_record
                dkim
                spf
              }
              source $(local_domains) {
                reject 501 5.1.8 "Use Submission for outgoing SMTP"
              }
              default_source {
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  reject 550 5.1.1 "User doesn't exist"
                }
              }
            }

            submission tcp://0.0.0.0:587 {
              limits {
                all rate 50 1s
              }
              auth &local_authdb
              source $(local_domains) {
                check {
                  authorize_sender {
                    prepare_email &local_rewrites
                    user_to_email identity
                  }
                }
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  modify {
                    dkim $(primary_domain) $(local_domains) default
                  }
                  deliver_to &remote_queue
                }
              }
              default_source {
                reject 501 5.1.8 "Non-local sender domain"
              }
            }

            target.remote outbound_delivery {
              limits {
                destination rate 20 1s
                destination concurrency 10
              }
              mx_auth {
                dane
                mtasts {
                  cache fs
                  fs_dir mtasts_cache/
                }
                local_policy {
                  min_tls_level encrypted
                  min_mx_level none
                }
              }
            }

            target.queue remote_queue {
              target &outbound_delivery
              autogenerated_msg_domain $(primary_domain)
              bounce {
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
                }
              }
            }

            imap tcp://0.0.0.0:143 {
              auth &local_authdb
              storage &local_mailboxes
            }
          '';
        };

        systemd.services.maddy-ldap-env = {
          description = "Render maddy's lldap bind EnvironmentFile from the agenix secret";
          requiredBy = [ "maddy.service" ];
          before = [ "maddy.service" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            LoadCredential = [ "bind:${bindPasswordFile}" ];
            RuntimeDirectory = "maddy-ldap";
            RuntimeDirectoryMode = "0700";
          };
          script = ''
            set -euo pipefail
            umask 077
            printf 'LLDAP_BIND_PW=%s\n' "$(cat "$CREDENTIALS_DIRECTORY/bind")" \
              > "$RUNTIME_DIRECTORY/env"
          '';
        };

        services.nginx = {
          enable = true;
          virtualHosts.${fqdn}.locations."/.well-known/acme-challenge".root = "/var/lib/acme/acme-challenge";
        };
        security.acme = {
          acceptTerms = true;
          defaults.email = "aforemny@posteo.de";
          certs.${fqdn} = {
            webroot = "/var/lib/acme/acme-challenge";
            group = "maddy";
            reloadServices = [ "maddy.service" ];
          };
        };
        systemd.services."acme-${fqdn}" = {
          after = [ "nginx.service" ];
          wants = [ "nginx.service" ];
        };

        networking.firewall.allowedTCPPorts = [
          80
          443
        ];

        # Published as mail.nomath.org by src/dns.nix; the MX record itself is
        # provisioned manually at the registrar (see the header).
        dns.dynamicAAAA = [ "mail" ];

        state.directories = [
          "/var/lib/maddy"
          "/var/lib/acme"
        ];
      }
    )
  ];
}
