{
  # Outbound-mail DNS: the MX / SPF / DMARC records are provisioned declaratively
  # via the declarative-runtime hetzner-dns pairing (records block below;
  # src/dns.nix enables the reconciler). The AAAA for mail.nomath.org is kept
  # current by set-hetzner-dns through dns.dynamicAAAA. Two records still cannot
  # be set from here: the DKIM TXT (maddy generates the key at runtime -- publish
  # the value it prints under /var/lib/maddy/dkim_keys/nomath.org_default.dns)
  # and the reverse PTR for the host's IPv6 (owned by the ISP's reverse zone, not
  # Hetzner). Without those two, strict receivers may still reject this mail.
  systems.tower.modules = [
    (
      { config, ... }:
      let
        fqdn = "mail.nomath.org";
        domain = "nomath.org";
        bindDn = "uid=admin,ou=people,dc=nomath,dc=org";
        bindPasswordFile = config.age.secrets.lldap-admin-password.path;
      in
      {
        services.maddy = {
          enable = true;
          hostname = fqdn;
          primaryDomain = domain;
          localDomains = [ domain ];
          openFirewall = true; # 25 (SMTP), 143 (IMAP+STARTTLS), 587 (submission)

          tls = {
            loader = "file";
            certificates = [
              {
                certPath = "/var/lib/acme/${fqdn}/fullchain.pem";
                keyPath = "/var/lib/acme/${fqdn}/key.pem";
              }
            ];
          };

          secrets = [ "/run/maddy-ldap/env" ];

          config = ''
            auth.ldap local_authdb {
              urls ldap://127.0.0.1:3890
              bind plain "${bindDn}" "{env:LLDAP_BIND_PW}"
              base_dn "ou=people,dc=nomath,dc=org"
              filter "(&(objectClass=person)(|(uid={username})(mail={username})))"
              starttls off
            }

            storage.imapsql local_mailboxes {
              driver sqlite3
              dsn imapsql.db
            }

            table.chain local_rewrites {
              optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
              optional_step static {
                entry postmaster postmaster@$(primary_domain)
              }
              optional_step file /etc/maddy/aliases
            }

            msgpipeline local_routing {
              destination postmaster $(local_domains) {
                modify {
                  replace_rcpt &local_rewrites
                }
                deliver_to &local_mailboxes
              }
              default_destination {
                reject 550 5.1.1 "User doesn't exist"
              }
            }

            smtp tcp://0.0.0.0:25 {
              limits {
                all rate 20 1s
                all concurrency 10
              }
              dmarc yes
              check {
                require_mx_record
                dkim
                spf
              }
              source $(local_domains) {
                reject 501 5.1.8 "Use Submission for outgoing SMTP"
              }
              default_source {
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  reject 550 5.1.1 "User doesn't exist"
                }
              }
            }

            submission tcp://0.0.0.0:587 {
              limits {
                all rate 50 1s
              }
              auth &local_authdb
              source $(local_domains) {
                check {
                  authorize_sender {
                    prepare_email &local_rewrites
                    user_to_email identity
                  }
                }
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  modify {
                    dkim $(primary_domain) $(local_domains) default
                  }
                  deliver_to &remote_queue
                }
              }
              default_source {
                reject 501 5.1.8 "Non-local sender domain"
              }
            }

            target.remote outbound_delivery {
              limits {
                destination rate 20 1s
                destination concurrency 10
              }
              mx_auth {
                dane
                mtasts {
                  cache fs
                  fs_dir mtasts_cache/
                }
                local_policy {
                  min_tls_level encrypted
                  min_mx_level none
                }
              }
            }

            target.queue remote_queue {
              target &outbound_delivery
              autogenerated_msg_domain $(primary_domain)
              bounce {
                destination postmaster $(local_domains) {
                  deliver_to &local_routing
                }
                default_destination {
                  reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
                }
              }
            }

            imap tcp://0.0.0.0:143 {
              auth &local_authdb
              storage &local_mailboxes
            }
          '';
        };

        systemd.services.maddy-ldap-env = {
          description = "Render maddy's lldap bind EnvironmentFile from the agenix secret";
          requiredBy = [ "maddy.service" ];
          before = [ "maddy.service" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            LoadCredential = [ "bind:${bindPasswordFile}" ];
            RuntimeDirectory = "maddy-ldap";
            RuntimeDirectoryMode = "0700";
          };
          script = ''
            set -euo pipefail
            umask 077
            printf 'LLDAP_BIND_PW=%s\n' "$(cat "$CREDENTIALS_DIRECTORY/bind")" \
              > "$RUNTIME_DIRECTORY/env"
          '';
        };

        services.nginx = {
          enable = true;
          virtualHosts.${fqdn}.locations."/.well-known/acme-challenge".root = "/var/lib/acme/acme-challenge";
        };
        security.acme = {
          acceptTerms = true;
          defaults.email = "aforemny@posteo.de";
          certs.${fqdn} = {
            webroot = "/var/lib/acme/acme-challenge";
            group = "maddy";
            reloadServices = [ "maddy.service" ];
          };
        };
        systemd.services."acme-${fqdn}" = {
          after = [ "nginx.service" ];
          wants = [ "nginx.service" ];
        };

        networking.firewall.allowedTCPPorts = [
          80
          443
        ];

        # AAAA for mail.nomath.org, kept in sync by set-hetzner-dns.
        dns.dynamicAAAA = [ "mail" ];

        # Static mail records, provisioned via the hetzner-dns reconciler that
        # src/dns.nix enables. DKIM and PTR are excluded on purpose (see header).
        services.hetzner-dns.runtime = {
          # MX -> mail.nomath.org. Trailing dot = absolute; Hetzner appends the
          # zone to a dotless name. `zone` is the literal domain (managed in the
          # Hetzner console, not by this reconciler), so no hcloud_zone is
          # declared for it -- declaring it would make tofu try to re-create the
          # existing zone and fail.
          zone_rrsets.mx = {
            zone = domain;
            name = "@";
            type = "MX";
            records = [ { value = "10 ${fqdn}."; } ];
          };
          # DMARC monitor-only (p=none): publishes a policy and collects reports
          # without risking rejection of legitimate mail during rollout.
          zone_rrsets.dmarc = {
            zone = domain;
            name = "_dmarc";
            type = "TXT";
            records = [ { value = ''"v=DMARC1; p=none; rua=mailto:postmaster@${domain}"''; } ];
          };
          # SPF authorises the MX host's address (this box's published AAAA).
          # Managed as a full apex-TXT RRSet rather than a single
          # hcloud_zone_record: hcloud_zone_record can only be adopted via
          # Terraform resource identity, which the reconciler's CLI `tofu import`
          # cannot supply, so on a lost/rebuilt tfstate (this box rolls / back on
          # boot) it fails re-adding the already-present SPF value with
          # "duplicate value" (HTTP 422) and never reconciles. An RRSet imports
          # by "<zone>/<name>/<type>" and adopts cleanly. The catch: an RRSet
          # owns *every* value at @/TXT, so the unrelated, externally-set
          # google-site-verification token must be listed here too or the apply
          # would delete it. Update it if Search Console ever re-issues one.
          zone_rrsets.apex_txt = {
            zone = domain;
            name = "@";
            type = "TXT";
            records = [
              { value = ''"v=spf1 mx ~all"''; }
              { value = ''"google-site-verification=krouLLrAV68-Bw5gN7qr8oN-u_tq5g5bqA9bn1U7z3o"''; }
            ];
          };
        };

        state.directories = [
          "/var/lib/maddy"
          "/var/lib/acme"
        ];
      }
    )
  ];
}
